### ISSUE TITLE
Instructions for proposing a Birds of a Feather / Special Interest Group

### ISSUE THREAD

**Issue by lwaldron** [Bioconductor/BioC2018#3]
We invite participants to form groups dedicated to discuss or work on topics of interest. We will make rooms available for groups to meet during the lunch breaks. We encourage students, postdocs and junior faculty to participant and form groups.

To create a special interest group open an issue describing the topic. The issue title should start with SIG: followed by a short but descriptive title. In the issue, include:

* An introduction of yourself.
* A description of the topic.
* Whether it should be held during Developer Day (Wednesday July 25) or the conference days (July 26-27).
* Desired outputs (could be code, a piece of documentation, or general discussion), and possible outcomes.

Interested participants should use the issue to ask questions and/or express their interest in participating. Proposals with interest shown by at least 3 additional participants by July 12 will be announced on the conference web page, and will have a room reserved for their meeting.

**Comment by mtmorgan** [comment]
This material is already on the [web site][1], so I'm closing it here.

[1]: http://bioc2018.bioconductor.org/call-for-abstracts.html
